### ISSUE TITLE
Hey. Can I join the development of this game?

### ISSUE THREAD

**Issue by psqq** [kosinaz/spectrl#1]

**Comment by kosinaz** [comment]
Sure thing! Let me add a game design document draft to let us be on the same page. In the meantime, feel free to share your initial ideas.
I'm also interested in how did you find this project and what made you decide to contribute.

**Comment by psqq** [comment]
Thnaks. I love to make games. 😄  I found your project by requesting "roguelike", sorting the results by update date. I think programming together is much more interesting!

**Comment by kosinaz** [comment]
Nice! Check the [game design.md](https://github.com/kosinaz/spectrl/blob/master/game%20design.md)! I will add more details later.

**Comment by kosinaz** [comment]
The game jam I made this game for just ended, and for now, I'm planning to head back to my main project, but thanks for your intention.
